/* AZ Travel Portal - Users Database (Client-side) */
/* هذا الملف يحتوي على بيانات المستخدمين - يمكن تعديله */
const USERS_DB = {
"admin":{"password":"admin123","full_name":"System Admin","role":"admin"},
"ahmed.ali":{"password":"Az@2026Ah","full_name":"أحمد علي","role":"admin"},
"mohamed.hassan":{"password":"Az@2026Mo","full_name":"محمد حسن","role":"admin"},
"omar.farouk":{"password":"Az@2026Om","full_name":"عمر فاروق","role":"admin"},
"ali.mahmoud":{"password":"Az@2026Al","full_name":"علي محمود","role":"viewer"},
"hassan.ibrahim":{"password":"Az@2026Ha","full_name":"حسن ابراهيم","role":"viewer"},
"youssef.ahmed":{"password":"Az@2026Yo","full_name":"يوسف احمد","role":"viewer"},
"khaled.mostafa":{"password":"Az@2026Kh","full_name":"خالد مصطفى","role":"viewer"},
"amr.abdallah":{"password":"Az@2026Am","full_name":"عمرو عبدالله","role":"viewer"},
"tamer.ali":{"password":"Az@2026Ta","full_name":"تامر علي","role":"viewer"},
"mahmoud.farouk":{"password":"Az@2026Ma","full_name":"محمود فاروق","role":"viewer"},
"mostafa.hassan":{"password":"Az@2026Ms","full_name":"مصطفى حسن","role":"viewer"},
"ibrahim.ahmed":{"password":"Az@2026Ib","full_name":"ابراهيم احمد","role":"viewer"},
"hesham.ali":{"password":"Az@2026He","full_name":"هشام علي","role":"viewer"},
"wael.mostafa":{"password":"Az@2026Wa","full_name":"وائل مصطفى","role":"viewer"},
"ayman.hassan":{"password":"Az@2026Ay","full_name":"ايمن حسن","role":"viewer"},
"samir.ali":{"password":"Az@2026Sa","full_name":"سمير علي","role":"viewer"},
"reda.farouk":{"password":"Az@2026Re","full_name":"رضا فاروق","role":"viewer"},
"gamal.ahmed":{"password":"Az@2026Ga","full_name":"جمال احمد","role":"viewer"},
"adel.hassan":{"password":"Az@2026Ad","full_name":"عادل حسن","role":"viewer"},
"hatem.ali":{"password":"Az@2026Hat","full_name":"حاتم علي","role":"viewer"},
"sherif.mostafa":{"password":"Az@2026Sh","full_name":"شريف مصطفى","role":"viewer"},
"basem.hassan":{"password":"Az@2026Bas","full_name":"باسم حسن","role":"viewer"},
"nader.ali":{"password":"Az@2026Na","full_name":"نادر علي","role":"viewer"},
"islam.ahmed":{"password":"Az@2026Is","full_name":"اسلام احمد","role":"viewer"},
"ashraf.hassan":{"password":"Az@2026Ash","full_name":"اشرف حسن","role":"viewer"},
"walid.ali":{"password":"Az@2026Wal","full_name":"وليد علي","role":"viewer"},
"fady.mostafa":{"password":"Az@2026Fa","full_name":"فادي مصطفى","role":"viewer"},
"maged.hassan":{"password":"Az@2026Mag","full_name":"ماجد حسن","role":"viewer"},
"ramy.ali":{"password":"Az@2026Ra","full_name":"رامي علي","role":"viewer"},
"ehab.ahmed":{"password":"Az@2026Eh","full_name":"ايهاب احمد","role":"viewer"},
"saeed.hassan":{"password":"Az@2026Sae","full_name":"سعيد حسن","role":"viewer"},
"emad.ali":{"password":"Az@2026Em","full_name":"عماد علي","role":"viewer"},
"fathy.mostafa":{"password":"Az@2026Fath","full_name":"فتحي مصطفى","role":"viewer"},
"sayed.hassan":{"password":"Az@2026Sey","full_name":"سيد حسن","role":"viewer"},
"abdelrahman.ali":{"password":"Az@2026Abr","full_name":"عبدالرحمن علي","role":"viewer"},
"hany.ahmed":{"password":"Az@2026Han","full_name":"هاني احمد","role":"viewer"},
"mohsen.hassan":{"password":"Az@2026Moh","full_name":"محسن حسن","role":"viewer"},
"lotfy.ali":{"password":"Az@2026Lot","full_name":"لطفي علي","role":"viewer"},
"galal.mostafa":{"password":"Az@2026Gal","full_name":"جلال مصطفى","role":"viewer"},
"shawky.hassan":{"password":"Az@2026Shaw","full_name":"شوقى حسن","role":"viewer"}
};
